src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $technicien;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $demandeur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_echeance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $priorite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getTechnicien(): ?string
    {
        return $this->technicien;
    }

    public function setTechnicien(string $technicien): self
    {
        $this->technicien = $technicien;

        return $this;
    }

    public function getDemandeur(): ?string
    {
        return $this->demandeur;
    }

    public function setDemandeur(string $demandeur): self
    {
        $this->demandeur = $demandeur;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->date_echeance;
    }

    public function setDateEcheance(\DateTimeInterface $date_echeance): self
    {
        $this->date_echeance = $date_echeance;

        return $this;
    }

    public function getPriorite(): ?string
    {
        return $this->priorite;
    }

    public function setPriorite(?string $priorite): self
    {
        $this->priorite = $priorite;

        return $this;
    }
}

src/Controller/ChefController.php
<?php

namespace App\Controller;

use App\Repository\TicketRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\Security;

class ChefController extends AbstractController
{
    /**
     * @var UrlGeneratorInterface
     */
    private $urlGenerator;
    /**
     * @var TicketRepository
     */
    private $ticketRepository;
    /**
     * @var Security
     */
    private $security;

    public function __construct(UrlGeneratorInterface $urlGenerator, TicketRepository $ticketRepository, Security $security)
    {
        $this->urlGenerator = $urlGenerator;
        $this->ticketRepository = $ticketRepository;
        $this->security = $security;
    }

    public function index()
    {
        $user = $this->security->getUser();

        if ($user) {
            dump($this->ticketRepository->findAll());
            return $this->ticketRepository->findAll();
        } else return new RedirectResponse($this->urlGenerator->generate('app_login'));
    }
}

templates/chef/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue{% endblock %}
{% block body %}

    {% if tickets is not defined %}
        <div>
            <h3>
                Il n'existe aucun ticket dans la base de données pour l'instant.
            </h3>
        </div>
    {% else %}
        <div class="d-flex justify-content-center table-responsive">

        <div class="col-sm-12 col-md-10 pt-4">
            <div class="container-fluid">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Statut</th>
                        <th scope="col">Titre</th>
                        <th scope="col">Technicien</th>
                        <th scope="col">Demandeur</th>
                        <th scope="col">Lieu</th>
                        <th scope="col">Date d'échéance</th>
                        <th scope="col">Priorité</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ticket in tickets %}
                        <tr>
                            <td>{{ ticket.id }}</td>
                            <td>{{ ticket.statut }}</td>
                            <td>{{ ticket.titre }}</td>
                            <td>{{ ticket.technicien }}</td>
                            <td>{{ ticket.demandeur }}</td>
                            <td>{{ ticket.lieu }}</td>
                            <td>{{ ticket.dateEcheance|date("d/m/Y") }}</td>
                            <td>{{ ticket.priorite }}</td>
                        </tr>
                    {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

    </div>

{% endblock %}